spring:
  data:
    mongodb:
      database: testdb
      host: localhost
      port: 27017
  devtools:
    restart: 
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false
server:
  port: 8081

